name: flutter_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl:
  bloc:
  flutter_bloc:
  dartz:
  http:
  equatable:
  shared_preferences:
  cached_network_image:

  # intl: ^0.18.1
  # bloc: ^8.1.2
  # flutter_bloc: ^8.1.3
  # dartz: ^0.10.1
  # http: ^1.1.2
  # equatable: ^2.0.5  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/fonts/
    - lib/assets/db/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf

        #   - family: Trajan Pro
        #     fonts:
        #       - asset: fonts/TrajanPro.ttf
        #       - asset: fonts/TrajanPro_Bold.ttf
        #         weight: 700
        #
        # For details regarding fonts from package dependencies,
        # see https://flutter.dev/custom-fonts/#from-packages
